services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "5555:5555"
      - "5900:5900"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=amazon_scraper.settings
      - DISPLAY=:99
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
