# Generated by Django 5.1.5 on 2025-01-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
